# dev/prod/test + setting file (dynamic variables)
# multiple modules
# API, form, vo, dao, ..., etc.
# each topics for spring boot.

# https://dev.to/mhdzaid/how-to-configure-profiles-in-spring-boot-16jo
# https://www.gushiciku.cn/pl/2Wno/zh-tw


# mvn package -P {dev} or ./mvnw package -P {dev}
# mvn package -P {prod} or ./mvnw package -P {prod}
# mvn package -P {test} or ./mvnw package -P {test}

spring:
  profiles:
    active: dev

  jackson:
    time-zone: UTC
      
software:
    name: spring-architecture
    version: 0.0.1
test:
    name: george
    age: 30


# # 配置執行緒池設定檔
# # https://ithelp.ithome.com.tw/articles/10278638
# spring.task.pool.corePoolSize=5
# spring.task.pool.maxPoolSize=50
# spring.task.pool.keepAliveSeconds=60
# spring.task.pool.queueCapacity=10000
# spring.task.pool.threadNamePrefix=Wesiting-Thread-